# Generated by Django 5.2.1 on 2026-05-31 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "biological_sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "M"), ("F", "F"), ("OTHER", "OTHER")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("height_cm", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "first_name"],
                        name="patients_pa_doctor__a1dfb4_idx",
                    ),
                    models.Index(
                        fields=["doctor", "-created_at"],
                        name="patients_pa_doctor__7259af_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("birth_date__isnull", False)),
                        fields=("doctor", "first_name", "birth_date"),
                        name="unique_patient_name_dob_per_doctor",
                    )
                ],
            },
        ),
    ]
