# Generated by Django 5.2.1 on 2026-05-31 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=40)),
                ("duration_min", models.PositiveSmallIntegerField()),
                ("performed_at", models.DateTimeField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-performed_at"],
                        name="health_logs_patient_144ae2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NutritionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("logged_at", models.DateTimeField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_notes",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-logged_at"],
                        name="health_logs_patient_0b8476_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SleepLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_hours", models.DecimalField(decimal_places=2, max_digits=4)),
                ("quality_score", models.PositiveSmallIntegerField()),
                ("started_at", models.DateTimeField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sleep_logs",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-started_at"],
                        name="health_logs_patient_55a48e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeightLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_kg", models.DecimalField(decimal_places=2, max_digits=5)),
                ("measured_at", models.DateTimeField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_logs",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-measured_at"],
                        name="health_logs_patient_9be854_idx",
                    )
                ],
            },
        ),
    ]
